In [1]:
import numpy as np

## Elementwise Operations

In [2]:
a  = np.array([[1,2,3], [4,5,6]])
b  = np.array([[1,2,3], [4,5,6]])

In [6]:
a + b #np.add()

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [7]:
a - b #np.subtract()

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
a * b #np.multiply()

array([[ 1,  4,  9],
       [16, 25, 36]])

In [9]:
a ** b #np.square, np.power()

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [10]:
a % 3  #np.divmod()

array([[1, 2, 0],
       [1, 2, 0]], dtype=int32)

In [11]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### Trigonometric Operation

In [18]:
new = np.sin(a)
new

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [19]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [20]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [21]:
1 / np.sin(a)

array([[ 1.18839511,  1.09975017,  7.0861674 ],
       [-1.32134871, -1.04283521, -3.57889955]])

In [22]:
1 / np.tan(a)

array([[ 0.64209262, -0.45765755, -7.01525255],
       [ 0.86369115, -0.29581292, -3.436353  ]])

### Round Operations

In [25]:
new

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [26]:
np.round(new)

array([[ 1.,  1.,  0.],
       [-1., -1., -0.]])

In [27]:
np.around(new, 3)

array([[ 0.841,  0.909,  0.141],
       [-0.757, -0.959, -0.279]])

In [28]:
np.rint(new)

array([[ 1.,  1.,  0.],
       [-1., -1., -0.]])

In [29]:
np.fix(new) #Rounds off towards 0

array([[ 0.,  0.,  0.],
       [-0., -0., -0.]])

In [30]:
np.floor(new) 

array([[ 0.,  0.,  0.],
       [-1., -1., -1.]])

### Exponential Functions

In [31]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [32]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

## Matrix Operations

In [41]:
c  = np.array([[1,2], [4,5]])
d  = np.array([[3,6], [8,9]])

In [42]:
c, d

(array([[1, 2],
        [4, 5]]),
 array([[3, 6],
        [8, 9]]))

In [43]:
np.dot(c, d)

array([[19, 24],
       [52, 69]])

In [45]:
np.transpose(d)

array([[3, 8],
       [6, 9]])

In [47]:
d.transpose()

array([[3, 8],
       [6, 9]])

In [49]:
d.T

array([[3, 8],
       [6, 9]])

In [50]:
np.trace(c)

6

In [52]:
np.linalg.det(c)

-2.9999999999999996

In [53]:
np.linalg.inv(c)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [60]:
# A . A^(-1) = I
np.dot(c, np.linalg.inv(c)).round()

array([[1., 0.],
       [0., 1.]])

In [62]:
np.linalg.eig(c)

EigResult(eigenvalues=array([-0.46410162,  6.46410162]), eigenvectors=array([[-0.80689822, -0.34372377],
       [ 0.59069049, -0.9390708 ]]))

In [63]:
#Solve Equations

e = np.array([[1,2], [3,5]])
f = np.array([1,2])
np.linalg.solve(e,f)

array([-1.,  1.])