In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
print(arr[0])

1


In [6]:
print(arr[1::2])
print(arr[::-1])

[2 4]
[4 3 2 1]


In [22]:
arr2 = np.random.randint(low = 1, high = 50, size = (4,4))
arr2

array([[18, 38, 28, 44],
       [43,  4, 23, 48],
       [12,  8, 15,  8],
       [11, 25, 38, 16]], dtype=int32)

In [24]:
print(arr2[0][2])
print(arr2[1][1])
print(arr2[2][3])

28
4
8


In [29]:
#print(row slicing, column slicing)
print(arr2[1:3:1, :])

[[43  4 23 48]
 [12  8 15  8]]


In [30]:
print(arr2[1:3:1, 1:3:1])

[[ 4 23]
 [ 8 15]]


In [52]:
arr3 = np.random.randint(low = 1, high = 50, size = (2,4,4))
arr3

array([[[24,  2, 25, 11],
        [32, 44, 36,  7],
        [11, 13, 23, 48],
        [49, 43, 49, 33]],

       [[ 9, 22,  9, 41],
        [35, 28, 47, 23],
        [38, 29, 39, 30],
        [ 2, 24, 32, 41]]], dtype=int32)

In [53]:
print(arr3[0][2])
print(arr3[1][1])

[11 13 23 48]
[35 28 47 23]


In [54]:
print(arr3[0,2,2])
print(arr3[0,1,3])
print(arr3[1,2,2])
print(arr3[1,1,0])

23
7
39
35


In [55]:
print(arr3[0,:2,:2])

[[24  2]
 [32 44]]


In [56]:
print(arr3[::2,:4,:4])

[[[24  2 25 11]
  [32 44 36  7]
  [11 13 23 48]
  [49 43 49 33]]]


In [59]:
print(arr3[-1, 0:-2,:3])

[[ 9 22  9]
 [35 28 47]]


In [49]:
print(arr3[::-1,:])
print(arr3[::-1,::-1])

[[[30 14  5  1]
  [27 39 48 38]
  [ 7 35  1  1]
  [10 15 13  8]]

 [[27 23 15 11]
  [20 42 42 36]
  [32 22 38 40]
  [31 32  2  8]]]
[[[10 15 13  8]
  [ 7 35  1  1]
  [27 39 48 38]
  [30 14  5  1]]

 [[31 32  2  8]
  [32 22 38 40]
  [20 42 42 36]
  [27 23 15 11]]]


In [61]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [65]:
mask = a < 4
print(mask)
print(a[mask])

[[ True  True]
 [ True False]
 [False False]]
[1 2 3]


In [66]:
mask1 = np.array([True, False, True])
print(a[mask1])

[[1 2]
 [5 6]]
