In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 4.2 MB/s eta 0:00:03
   -------------------- ------------------- 6.3/12.6 MB 20.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 30.3 MB/s eta 0:00:00


In [2]:
import numpy as np

## Creating numpy array

In [3]:
lst = [1,4,7,3,1]

In [4]:
arr = np.array([1,4,7,3,1])
arr

array([1, 4, 7, 3, 1])

In [5]:
arr1 = np.array(lst)
arr1

array([1, 4, 7, 3, 1])

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(arr)
print(arr.ndim)
print(arr.shape)

[1 4 7 3 1]
1
(5,)


In [8]:
lst2 = [
            [1,2,3],
            [4,5,6]
       ]

In [9]:
arr2 = np.array(lst2)

In [10]:
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64


In [11]:
z_arr = np.zeros(3)
print(z_arr)

[0. 0. 0.]


In [12]:
z_arr1 = np.zeros((3,3))
print(z_arr1)
print(z_arr1.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


In [13]:
o_arr = np.ones(5)
o_arr

array([1., 1., 1., 1., 1.])

In [14]:
o_arr1 = np.ones((5,3))
o_arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
i_arr = np.identity(5)
i_arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
eye_arr = np.eye(4,4)
eye_arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
eye_arr1 = np.eye(4,6)
eye_arr1

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [18]:
np.random.rand(3,4)

array([[0.90298475, 0.937471  , 0.33678408, 0.44351107],
       [0.80922391, 0.37676065, 0.64841965, 0.77740256],
       [0.8442911 , 0.25839431, 0.01327832, 0.82245143]])

In [19]:
x = np.arange(5,55,5)
x

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [20]:
x.reshape(2,5)

array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50]])

In [21]:
np.arange(-3.4, 15.4, 2.1)

array([-3.4, -1.3,  0.8,  2.9,  5. ,  7.1,  9.2, 11.3, 13.4])

In [22]:
lin_arr = np.linspace(start=0, stop=10, num=6)
lin_arr

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [23]:
lin_arr1 = np.linspace(start=(0,0,0), stop=(10,20,30), num=6, axis=0)
lin_arr1

array([[ 0.,  0.,  0.],
       [ 2.,  4.,  6.],
       [ 4.,  8., 12.],
       [ 6., 12., 18.],
       [ 8., 16., 24.],
       [10., 20., 30.]])

In [24]:
lin_arr2 = np.linspace(start=(0,5,10), stop=(10,18,25), num=6, axis=1)
lin_arr2

array([[ 0. ,  2. ,  4. ,  6. ,  8. , 10. ],
       [ 5. ,  7.6, 10.2, 12.8, 15.4, 18. ],
       [10. , 13. , 16. , 19. , 22. , 25. ]])

In [25]:
d_arr = np.diag([1,2,3,4])
d_arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
d_arr1 = np.diag([1,2,3,4], k=1)
d_arr1

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [27]:
d_arr2 = np.diag([1,2,3,4], k=-1)
d_arr2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [28]:
nd_array = np.random.randint(low = 1, high = 25, size = (2,3,4))

In [29]:
nd_array.shape

(2, 3, 4)

In [30]:
nd_array

array([[[ 5, 19, 13,  9],
        [ 7,  5, 23, 11],
        [23, 17, 11, 21]],

       [[22, 17, 10,  6],
        [21,  5, 12, 16],
        [ 8, 20,  2,  2]]], dtype=int32)

In [31]:
nd_array1 = np.random.randint(low = 1, high = 25, size = (2,2,1,3))

In [32]:
nd_array1.shape

(2, 2, 1, 3)

In [33]:
nd_array1

array([[[[ 2, 24,  6]],

        [[21, 19, 21]]],


       [[[12, 18, 12]],

        [[21,  8,  5]]]], dtype=int32)