In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low = 1, high = 50, size = (2,4,4))
arr

array([[[40,  3, 39, 33],
        [10, 20, 48, 38],
        [ 7, 12, 18, 19],
        [ 2, 41, 39,  5]],

       [[ 7,  4, 16, 29],
        [39, 45, 23,  1],
        [27, 18, 21, 15],
        [32, 27, 24,  5]]])

In [3]:
arr.shape

(2, 4, 4)

In [4]:
arr.dtype

dtype('int32')

In [5]:
arr.ndim

3

In [6]:
arr.T

array([[[40,  7],
        [10, 39],
        [ 7, 27],
        [ 2, 32]],

       [[ 3,  4],
        [20, 45],
        [12, 18],
        [41, 27]],

       [[39, 16],
        [48, 23],
        [18, 21],
        [39, 24]],

       [[33, 29],
        [38,  1],
        [19, 15],
        [ 5,  5]]])

In [7]:
arr.reshape(4,2,4)

array([[[40,  3, 39, 33],
        [10, 20, 48, 38]],

       [[ 7, 12, 18, 19],
        [ 2, 41, 39,  5]],

       [[ 7,  4, 16, 29],
        [39, 45, 23,  1]],

       [[27, 18, 21, 15],
        [32, 27, 24,  5]]])

In [8]:
arr.flatten()

array([40,  3, 39, 33, 10, 20, 48, 38,  7, 12, 18, 19,  2, 41, 39,  5,  7,
        4, 16, 29, 39, 45, 23,  1, 27, 18, 21, 15, 32, 27, 24,  5])

In [9]:
arr.ravel()

array([40,  3, 39, 33, 10, 20, 48, 38,  7, 12, 18, 19,  2, 41, 39,  5,  7,
        4, 16, 29, 39, 45, 23,  1, 27, 18, 21, 15, 32, 27, 24,  5])

In [10]:
arr.sum()

707

In [11]:
arr2 = arr.sum(axis=1)
arr2

array([[ 59,  76, 144,  95],
       [105,  94,  84,  50]])

In [12]:
arr2.sum()

707

In [13]:
arr.max()

48

axis = 0 ---> column wise addition| axis = 1 ------> row wise addition

In [14]:
arr.prod(axis=1)

array([[   5600,   29520, 1314144,  119130],
       [ 235872,   87480,  185472,    2175]])

In [15]:
arr.argmax(axis=1)

array([[0, 3, 1, 1],
       [1, 1, 3, 0]], dtype=int64)

In [17]:
arr

array([[[40,  3, 39, 33],
        [10, 20, 48, 38],
        [ 7, 12, 18, 19],
        [ 2, 41, 39,  5]],

       [[ 7,  4, 16, 29],
        [39, 45, 23,  1],
        [27, 18, 21, 15],
        [32, 27, 24,  5]]])

In [16]:
arr.cumsum() #row wise

array([ 40,  43,  82, 115, 125, 145, 193, 231, 238, 250, 268, 287, 289,
       330, 369, 374, 381, 385, 401, 430, 469, 514, 537, 538, 565, 583,
       604, 619, 651, 678, 702, 707])

In [18]:
arr.cumsum(axis = 1)  #column wise

array([[[ 40,   3,  39,  33],
        [ 50,  23,  87,  71],
        [ 57,  35, 105,  90],
        [ 59,  76, 144,  95]],

       [[  7,   4,  16,  29],
        [ 46,  49,  39,  30],
        [ 73,  67,  60,  45],
        [105,  94,  84,  50]]])

In [19]:
a1 = np.random.randint(low = 1, high = 50, size = (2,3))
a2 = np.random.randint(low = 1, high = 50, size = (2,3))

In [22]:
a1, a2

(array([[42,  6, 19],
        [ 5, 33, 12]]),
 array([[45,  3, 12],
        [18, 33, 14]]))

In [24]:
#Vertical stack requires same no of columns of the matrix
np.vstack((a1, a2))

array([[42,  6, 19],
       [ 5, 33, 12],
       [45,  3, 12],
       [18, 33, 14]])

In [25]:
#Horizontal stack requires the same no of rows
np.hstack((a1, a2))

array([[42,  6, 19, 45,  3, 12],
       [ 5, 33, 12, 18, 33, 14]])