In [1]:
import numpy as np

In [6]:
arr = np.random.randint(low = 1, high = 50, size = (2,4,4))
arr

array([[[ 1, 38, 30,  2],
        [14, 31, 24,  7],
        [48, 35,  9, 41],
        [34, 39, 38, 34]],

       [[ 1, 16, 42, 49],
        [31, 49, 10, 35],
        [23, 33, 35,  4],
        [25, 43,  5, 23]]], dtype=int32)

In [7]:
arr.shape

(2, 4, 4)

In [9]:
arr.dtype

dtype('int32')

In [10]:
arr.ndim

3

In [11]:
arr.T

array([[[ 1,  1],
        [14, 31],
        [48, 23],
        [34, 25]],

       [[38, 16],
        [31, 49],
        [35, 33],
        [39, 43]],

       [[30, 42],
        [24, 10],
        [ 9, 35],
        [38,  5]],

       [[ 2, 49],
        [ 7, 35],
        [41,  4],
        [34, 23]]], dtype=int32)

In [12]:
arr.reshape(4,2,4)

array([[[ 1, 38, 30,  2],
        [14, 31, 24,  7]],

       [[48, 35,  9, 41],
        [34, 39, 38, 34]],

       [[ 1, 16, 42, 49],
        [31, 49, 10, 35]],

       [[23, 33, 35,  4],
        [25, 43,  5, 23]]], dtype=int32)

In [13]:
arr.flatten()

array([ 1, 38, 30,  2, 14, 31, 24,  7, 48, 35,  9, 41, 34, 39, 38, 34,  1,
       16, 42, 49, 31, 49, 10, 35, 23, 33, 35,  4, 25, 43,  5, 23],
      dtype=int32)

In [14]:
arr.ravel()

array([ 1, 38, 30,  2, 14, 31, 24,  7, 48, 35,  9, 41, 34, 39, 38, 34,  1,
       16, 42, 49, 31, 49, 10, 35, 23, 33, 35,  4, 25, 43,  5, 23],
      dtype=int32)

In [15]:
arr.sum()

np.int64(849)

In [19]:
arr2 = arr.sum(axis=1)
arr2

array([[ 97, 143, 101,  84],
       [ 80, 141,  92, 111]])

In [20]:
arr2.sum()

np.int64(849)

In [21]:
arr.max()

np.int32(49)

axis = 0 ---> column wise addition| axis = 1 ------> row wise addition

In [23]:
arr.prod(axis=1)

array([[  22848, 1607970,  246240,   19516],
       [  17825, 1112496,   73500,  157780]])

In [25]:
arr.argmax(axis=1)

array([[2, 3, 3, 2],
       [1, 1, 0, 0]])